{+forward-override{forward-socks5 127.0.0.1:1081 .}}
raspberrypi.org
hostus.us
s.w.org
sex8.cc
altrec.com
darpa.mil
fastpic.ru
fxnetworks.com
hulu.com
huluim.com
www.ilovelongtoes.com
muzu.tv
netflix.com
pandora.com
.pandora.tv
www.parkansky.com
.pimg.tw
pure18.com
rdio.com
slacker.com
spotify.com
target.com
turntable.fm
vevo.com
zattoo.com
qq.co.za
zozotown.com
.0rz.tw
0rz.tw
0to255.com
apple.com.tw
10musume.com
123rf.com
.12bet.com
12bet.com
.12vpn.com
12vpn.com
141hongkong.com
.173ng.com
173ng.com
1984bbs.com
.1984bbs.org
1984bbs.org
.1bao.org
1bao.org
1pondo.tv
.1eew.com
hand.info
.2000fun.com
.2008xianzhang.info
2008xianzhang.info
21andy.com
24smile.org
.2shared.com
.315lz.com
32red.com
36rain.com
4bluestones.biz
4chan.org
4shared.com
5i01.com
taiwannation.50webs.com
51.ca
.5maodang.com
4.net
64tianwang.com
64wiki.com
666kb.com
6park.com
www.6v6dota.com
7capture.com
.881903.com
.888.com
881903.com
64.org
.9001700.com
908taiwan.org
91porn.com
.92ccav.com
9bis.com
9bis.net
day.com
a5.com.ru
.abc.com
.ablwang.com
.aboluowang.com
aboluowang.com
.aboutgfw.com
acgkj.com
actimes.com.au
aculo.us
addictedtocoffee.de
adultfriendfinder.com
adultkeep.net
advanscene.com
advertfan.com
aenhancers.com
af.mil
aiph.net
.aisex.com
ait.org.tw
.aiweiweiblog.com
aiweiweiblog.com
ajaxplorer.info
www.ajsands.com
.akamaihd.net
online.com
qimmah.net
alabout.com
alasbarricadas.org
notes.alexdong.com
alexlur.org
aliengu.com
alkasir.com
allgirlsallowed.org
alliance.org.hk
.allinfa.com
allinfa.com
allinfo.com
allmovie.com
tools.com
alvinalexander.com
alwaysdata.com
alwaysdata.net
am730.com.hk
amazon.com
ameblo.jp
americangreencard.com
amiblockedornot.com
.amnesty.org
amnesty.org
.amnestyusa.org
amnestyusa.org
.amoiist.com
amzs.me
v.com
anchorfree.com
andfaraway.net
android.com
angularjs.org
animecrazy.net
anobii.com
.anonymizer.com
anontext.com
islam.org
anthonycalzadilla.com
.antiwave.net
antiwave.net
aobo.com.au
aolchannels.aol.com
video.aol.ca
video.aol.co.uk
video.aol.com
www.aolnews.com
aomiwang.com
video.ap.org
.apetube.com
apiary.io
.apigee.com
apigee.com
appledaily.com
archive.is
archive.org
.arctosia.com
arctosia.com
backup.org
army.mil
artsy.net
.asahichinese.com
asahichinese.com
asdfg.jp
.asiaharvest.org
asiaharvest.org
asianews.it
asianwomensfilm.de
askstudent.com
.askynz.net
askynz.net
assembla.com
astonmartinnews.com
atc.org.au
.atchinese.com
atchinese.com
atgfw.org
atj.org.tw
.atlaspost.com
atlaspost.com
.atnext.com
atnext.com
avaaz.org
avdb.in
avidemux.org
avoision.com
axureformac.com
forum.baby
babynet.com.hk
backchina.com
.backpackers.com.tw
badoo.com
baidu.jp
baixing.me
hen.bao.li
bannedbook.org
barnabu.co.uk
bayvoice.net
dajusha.baywords.com
.bbc.co.uk*chinese
.bbc.co.uk
.bbc.co.uk*zhongwen
news.bbc.co.uk
newsforums.bbc.co.uk
.bbcchinese.com
bbcchinese.com
bbc.in
.bbg.gov
bbsfeed.com
bbsland.com
.bcc.com.tw
.bcchinese.net
.bebo.com
bebo.com
beijing1989.com
beijingspring.com
.berlintwitterwall.com
berlintwitterwall.com
.bestforchina.org
bestforchina.org
.bestvpnservice.com
bet365.com
.betfair.com
.bettween.com
bettween.com
betvictor.com
.bewww.net
bfnn.org
bfsh.hk
biantailajiao.com
biantailajiao.in
bigfools.com
.bignews.org
bignews.org
.bigsound.org
software.com
billypan.com
billywr.com
bipic.net
.bit.ly
bit.ly
bitcointalk.org
.bitshare.com
bitshare.com
bjzc.org
tor.blingblingsquad.net
.blinkx.com
blinkx.com
blinw.com
.blip.tv
blip.tv
.blockcn.com
blockcn.com
blog.de
blogblog.com
.blogcatalog.com
blogcatalog.com
.blogger.com
blogger.com
blogimg.jp
blog.kangye.org
.bloglines.com
bloglines.com
bloglovin.com
rconversation.blogs.com
blogtd.net
.blogtd.org
blogtd.org
bloodshed.net
.bloomberg.cn
bloomberg.cn
.bloomberg.com
bloomberg.com
bloomberg.de
bloomfortune.com
bnrmetal.com
boardreader.com
bonbonme.com
books.com.tw
.botanwang.com
.bot.nu
.bowenpress.com
bowenpress.com
dl.box.net
boxun.com
.boxun.tv
boxun.tv
boxunblog.com
br.st
brandonhutchinson.com
braumeister.org
.break.com
break.com
.breakingtweets.com
breakingtweets.com
.briefdream.com
brightkite.com
brizzly.com
broadbook.com
ibros.org
brucewang.net
bt95.com
btdigg.org
.budaedu.org
budaedu.org
.bullog.org
bullog.org
.bullogger.com
bullogger.com
.businessweek.com
.businesstimes.com.cn
businesstimes.com.cn
bugclub.org
buugaa.com
buzzurl.jp
bwsj.hk
bx.tl
holz.byethost8.com
spanvideo.org
simple.com
.cacnw.com
.cactusvpn.com
cactusvpn.com
.cafepress.com
.cahr.org.tw
.calameo.com
cn.calameo.com
cams.com
.cams.org.sg
canadameet.com
bbs.cantonese.asia
.canyu.org
.cao.im
.caobian.info
caobian.info
catcatbox.com
caochangqing.com
cari.com.my
catch22.net
catfightpayperview.xxx
.catholic.org.hk
catholic.org.hk
catholic.org.tw
.cbsnews.com
ccavtop10.com
.ccdtr.org
ccdtr.org
.ccim.org
cclife.org
.ccthere.com
.cctongbao.com
ccue.ca
ccue.com
.cgdepot.org
cgdepot.org
cdig.info
cdjp.org
.cdnews.com.tw
cdp1998.org
cdp2006.org
cdpusa.org
cdpweb.org
cdpwu.org
cdw.com
.cecc.gov
cecc.gov
cellulo.info
cenci.tk
cenews.eu
centralnation.com
.centurys.net
centurys.net
.cfhks.org.hk
.cftfc.com
chandoo.org
.change.org
change.org
.changp.com
changp.com
.chapm25.com
.chaturbate.com
chengmingmag.com
.chenguangcheng.com
chenguangcheng.com
chenpokong.com
cherrysave.com
chicagoncmtv.com
week.com
china101.com
china21.com
china21.org
.china5000.us
chinaaffairs.org
chinaaid.me
chinaaid.us
chinaaid.org
chinaaid.net
chinacomments.org
chinachange.org
chinachannel.hk
.chinadigitaltimes.net
chinadigitaltimes.net
.chinaeweekly.com
chinaeweekly.com
chinafreepress.org
.chinagate.com
chinageeks.org
chinagfw.org
.chinagreenparty.org
chinagreenparty.org
.chinahush.com
chinalawtranslate.com
chinaxchina.com
.chinainperspective.com
chinainperspective.net
.chinainperspective.org
chinainperspective.org
chinainterimgov.org
chinalawandpolicy.com
.chinamule.com
chinamule.com
chinamz.org
.chinarightsia.org
chinasocialdemocraticparty.com
chinasoul.org
chinatimes.com
chinatweeps.com
chinaway.org
.chinaworker.info
chinaworker.info
chinayouth.org.hk
chinayuanmin.org
hermit.net
memorial.org
chinesedailynews.com
.chinesen.de
chinesen.de
chinesenewsnet.com
.chinesepen.org
.chinesetalks.net
.chingcheong.com
chingcheong.com
chn.chosun.com
christianstudy.com
christusrex.org
hk.org
chrome.com
chromeadblock.com
chubun.com
chuizi.net
chrispederick.com
chrispederick.net
christiantimes.org.hk
.chrlawyers.hk
allaboutalpha.com
.circlethebayfortibet.org
.citizenlab.org
citizensradio.org
city9x.com
.civicparty.hk
civicparty.hk
civilhrfront.org
psiphon.civisec.org
cjb.net
.ck101.com
ck101.com
classicalguitarblog.net
.clb.org.hk
.clipfish.de
www.cmoinc.org
.cmule.com
cmule.com
cms.gov
cna.com.tw
.cnavista.com.tw
.cnd.org
cnd.org
wiki.cnitter.com
.cnn.com
news.cnyes.com
cochina.org
.code1984.com
codeshare.io
tosh.comedycentral.com
comefromchina.com
compileheart.com
conoyo.com
.contactmagazine.net
.coolaler.com
coolaler.com
coolder.com
coolloud.org.tw
corumcollege.com
couchdbwiki.com
cotweet.com
cpj.org
crackle.com
net.org
creaders.net
.crossthewall.net
crossthewall.net
csdparty.com
csuchen.de
cts.com.tw
.cuhkacs.org
.cuihua.org
cuihua.org
.cuiweiping.net
cuiweiping.net
curvefish.com
.culture.tw
culture.tw
forum.cyberctm.com
cyberghostvpn.com
cynscribe.com
cytode.us
ifan.cz.cc
mike.cz.cc
nic.cz.cc
cl.d0z.net
.dabr.co.uk
dabr.co.uk
dabr.mobi
dabr.me
dadazim.com
.dadi360.com
dafagood.com
dafahao.com
dalailama.ru
.dailidaili.com
dailidaili.com
.dailymotion.com
.dajiyuan.com
.dajiyuan.eu
dalailama.com
.dalailamaworld.com
dalailamaworld.com
dalianmeng.org
.danke4china.net
danke4china.net
.danwei.org
daolan.net
daxa.cn
cn.dayabook.com
.daylife.com
.ddc.com.tw
sci.org
lists.debian.org
packages.debian.org
delcamp.net
delicious.com
.democrats.org
democrats.org
desc.se
welle.de
dev102.com
deviantart.com
devio.us
devpn.com
www.dfanning.com
dfas.mil
.diaoyuislands.org
diaoyuislands.org
static.digg.com
digitalnomadsproject.org
.diigo.com
diigo.com
furl.net
.dipity.com
directcreative.com
.discuss.com.hk
discuss.com.hk
disp.cc
inc.us
.dizhidizhi.com
djangosnippets.org
laby.jp
dlsite.com
dmcdn.net
dnscrypt.org
dns2go.com
.dojin.com
forum.net
dolc.de
dollf.com
.domain.club.tw
dongde.com
dongtaiwang.com
.dongtaiwang.net
dongtaiwang.net
.dongyangjing.com
.dontfilter.us
dontmovetochina.com
.dotplane.com
dotplane.com
dotsub.com
doubleaf.com
dougscripts.com
dowei.org
doxygen.org
dphk.org
dpp.org.tw
weigegebyc.dreamhosters.com
drgan.net
dropbox.com
dropboxusercontent.com
drsunacademy.com
.drtuber.com
.dscn.info
dtiblog.com
dtic.mil
dtiserv2.com
duckduckgo.com
.duckload.com
duckmylife.com
.duihua.org
duihua.org
duihuahrjournal.org
.duoweitimes.com
duoweitimes.com
duping.net
duplicati.com
dupola.com
dupola.net
dvorak.org
.dw.de
dw.de
world.com
world.de
www.dwheeler.com
dwnews.com
dwnews.net
xys.dxiong.com
dy24k.info
dynawebinc.com
.dyndns.org
.dzze.com
gold.com
g.e
info.org.tw
traderland.net
.e123.hk
hkjp.easyweb.hk
ebookbrowse.com
ebookee.com
ecministry.net
bbs.ecstart.com
edicypages.com
edoors.com
.edubridge.com
edubridge.com
eevpn.com
efcc.org.hk
efmoe.com
av.com
electionsmeter.com
elpais.com
.eltondisney.com
emacsblog.org
.emory.edu
ed2k.com
.emuparadise.me
enewstree.com
chinese.engadget.com
englishfromengland.co.uk
entermap.com
bg.com
romania.com
epochtimes.co.il
epochtimes.co.kr
epochtimes.com
epochtimes.de
epochtimes.fr
.epochtimes.ie
epochtimes.jp
epochtimes.ru
epochtimes.se
epochtimestr.com
epochweekly.com
erabaru.net
.erepublik.com
ernestmandel.org
erights.net
etaiwannews.com
etizer.org
.ettoday.net
www.eulam.com
eventful.com
exblog.jp
blog.exblog.co.jp
www.exblog.jp
expatshield.com
exploader.net
.extremetube.com
eyevio.jp
.ezpc.tk
.ezpeer.com
.facebook.com
facebook.com
v6.facebook.com
connect.facebook.net
facesofnyfw.com
faiththedog.info
.fakku.net
falunart.org
falundafa.org
falundafamuseum.org
falunhr.org
fanglizhi.info
fangong.org
fangongheike.com
fanqianghou.com
fapdu.com
.fawanghuihui.org
fbcdn.net
fanqiangyakexi.net
fail.hk
famunion.com
qiang.com
.fangbinxing.com
fangbinxing.com
fangeming.com
fanswong.com
.fanyue.info
.farwestchina.com
fastly.net
favorious.com
en.favotter.net
faststone.org
favstar.fm
faydao.com
fb.com
fb.me
fbsbx.com
fc2.com
.fc2china.com
shifeike.blog125.fc2blog.net
video.fdbox.com
.fdc89.jp
fourface.nodesnoop.com
feedburner.com
feedzshare.com
feelssh.com
feer.com
feministteacher.com
.fengzhenghu.com
fengzhenghu.com
fflick.com
fgmtv.net
.fgmtv.org
.filefactory.com
.files2me.com
files2me.com
.fileserve.com
fillthesquare.org
finalion.jp
findbook.tw
finler.net
.fireofliberty.org
fireofliberty.org
.falsefire.com
falsefire.com
fleshbot.com
flickr.com
staticflickr.com
flickrhivemind.net
yuming.flnet.org
cn.fmnnow.com
blog.foolsmountain.com
www.forum4hk.com
worker.forums
4sq.com
fotop.net
video.foxbusiness.com
fringenetwork.com
flecheinthepeche.fr
focustaiwan.tw
.focusvpn.com
fofg.org
.fooooo.com
fooooo.com
footwiball.com
fourthinternational.org
foxdie.us
foxsub.com
foxtang.com
fqrouter.com
franklc.com
.freakshare.com
freakshare.com
free4u.com.ar
gate.org
.free.fr
allonlinux.free.fr
dimitrik.free.fr
kineox.free.fr
puttycm.free.fr
freealim.com
whitebear.freebearblog.org
.freechal.com
.freedomhouse.org
freedomhouse.org
.freegao.com
freegao.com
now.org
.freelotto.com
freelotto.com
freeman2.com
.freeopenvpn.com
freemoren.com
freemorenews.com
china.org
freenewscn.com
.freeoz.org
freeoz.org
www.bulbous.freeserve.co.uk
freessh.us
ssh.com
freenetproject.org
freetibet.org
freewallpaper4.me
.freewebs.com
freeweibo.com
.freexinwen.com
.freeyoutubeproxy.net
freeyoutubeproxy.net
friendfeed.com
media.com
ff.im
www.zensur.freerk.com
freevpn.nl
.fring.com
fring.com
frommel.net
.frontlinedefenders.org
fscked.org
.fsurf.com
.ftchinese.com
.fuckcnnic.net
fuckcnnic.net
fuckgfw.org
fulue.com
.funf.tw
funp.com
furinkan.com
.futurechinaforum.org
futuremessage.org
.fuyin.net
fw.cm
fzh999.com
fzh999.net
gabocorp.com
.gaeproxy.com
galenwu.com
game735.com
gamebase.com.tw
gamer.com.tw
.gamer.com.tw
.gamez.com.tw
gamez.com.tw
.gaoming.net
gaoming.net
ganges.com
.gaopi.net
gaopi.net
.gaozhisheng.org
.gaozhisheng.net
gardennetworks.com
gardennetworks.org
72.52.81.22
gartlive.com
gather.com
gaymap.cc
.gazotube.com
gazotube.com
gcc.org.hk
gclooney.com
.gcpnews.com
.gdbt.net
gdzf.org
art.net
geekerhome.com
geekmanuals.com
genuitec.com
.geocities.co.jp
.geocities.com
hk.geocities.com
geocities.jp
geohot.com
geometrictools.com
help.com
.getchu.com
getfoxyproxy.org
.getfreedur.com
.getlantern.org
getlantern.org
.getjetso.com
getiton.com
.getsocialscope.com
gfw.org.ua
.ggssl.com
ggssl.com
ghost.org
ghut.org
web.jp
cn.giganews.com
gigporno.ru
gimpshop.com
girlbanker.com
gist.github.com
glennhilton.com
globaljihad.net
globalmuseumoncommunism.org
globalrescue.net
.globalvoicesonline.org
globalvoicesonline.org
gmbd.cn
gmhz.org
gnci.org.hk
goagent.biz
goagentplus.com
godfootsteps.org
goldbetsports.com
www.goldenmelody.com.tw
goldwave.com
gongmeng.info
gongm.in
gongminliliang.com
.gongwt.com
.goodreads.com
goodreads.com
.goodreaders.com
goodreaders.com
goofind.com
.googlesile.com
.gopetition.com
gopetition.com
gotw.ca
grandtrial.org
graphis.ne.jp
greatfirewall.biz
greatfirewallofchina.net
.greatfirewallofchina.org
greatfirewallofchina.org
.greenparty.org.tw
gpass1.com
firewall.com
roc.org
greatroc.org
greatzhonghua.org
.greenvpn.net
greenvpn.net
discuss.com
gtricks.com
guancha.org
world.net
gutteruncensored.com
gvm.com.tw
.gzm.tv
anime.info
g.co
ggpht.com
gmail.com
gmodules.com
goo.gl
analytics.com
googleadservices.com
googleapis.com
googleearth.com
googlecode.com
googledrive.com
googlelabs.com
googlemail.com
googleplus.com
googlesource.com
googlesyndication.com
googletagmanager.com
googletagservices.com
googleusercontent.com
googlevideo.com
.appspot.com
appspot.com
echofon.com
golang.org
www.klip.me
site.locql.com
download.syniumsoftware.com
ub0.cc
wozy.in
anti.anti.cnn.googlepages.com
freegateget.googlepages.com
myboooks.googlepages.com
.googlevideo.com
gospelherald.com
hk.gradconnection.com
graylog2.org
greatfire.org
greatroc.tw
gstatic.com
.theguardian.co*
guishan.org
gunsamerica.com
.gyalwarinpoche.com
h1n1china.org
.hacken.cc
hackthatphone.net
hahlo.com
hakkatv.org.tw
.hanunyi.com
hardsextube.com
hasaowall.com
have8.com
haygo.com
hdtvb.net
heartyit.com
.hecaitou.net
hecaitou.net
.hechaji.com
hechaji.com
helplinfen.com
helloandroid.com
helloqueer.com
hellotxt.com
htxt.it
.hellouk.org
.helpeachpeople.com
helpeachpeople.com
.helpzhuling.org
date.fm
flightcaster.com
branch.com
awardwinningfjords.com
futureme.org
getcloudapp.com
cl.ly
f.cl.ly
getsmartlinks.com
scm.com
lesscss.org
list.ly
maxgif.com
overlapr.com
peerpong.com
pose.com
samsoff.es
sendoid.com
speckleapp.com
stuffimreading.net
tomayko.com
twt.fm
views.fm
heqinglian.net
here4news.com
heungkongdiscuss.com
app.heywire.com
.hgseav.com
advent.org
hidecloud.com
.hidemyass.com
hidemyass.com
hideipvpn.com
.hihiforum.com
hihiforum.com
hihistory.net
.higfw.com
highrockmedia.com
hikinggfw.org
.himemix.com
himemix.com
.himemix.net
times.hinet.net
.hjclub.info
pub.com
.hk32168.com
hk32168.com
app.hkatvnews.com
hkbc.net
.hkbf.org
.hkchurch.org
hkday.net
.hkdailynews.com.hk
.hkej.com
.hkepc.com
global.hkepc.com*forum
hkfront.org
hkgolden.com
.hkgreenradio.org
.hkheadline.com*blog
.hkheadline.com
hkhkhk.com
hkjc.com
.hkjp.org
hkptu.org
.hkreporter.com
hkreporter.com
.hkwcc.org.hk
hkzone.org
apps.hloli.net
hnjhj.com
hola.com
holyspiritspeaks.org
derekhsu.homeip.net
homeservershow.com
hongmeimei.com
hongzhi.li
hootsuite.com
hotfile.com
hotpot.hk
.hotshame.com
hotspotshield.com
hougaige.com
howtoforge.com
.hqcdp.org
hqcdp.org
.hrcir.com
.hrichina.org
hrichina.org
.hrw.org
hrw.org
hsjp.net
hsselite.com
.htkou.net
htmldog.com
huaglad.com
.huanghuagang.org
huanghuagang.org
.huaren.us
news.com
huaxin.ph
yue.net
hugoroy.eu
t.huhaitai.com
ya.com
hungerstrikeforaids.org
huping.net
hutianyi.net
hutong9.net
hwinfo.com
hypeshell.com
hyperrate.com
i1.hk
i2p2.de
i2runner.com
iask.ca
iask.bz
ibiblio.org
f.net
cn.ibtimes.com
blogs.icerocket.com
.icij.org
fi.org
iconpaper.org
w.idaiwan.com
idemocracy.asia
.identi.ca
identi.ca
idiomconnection.com
www.idlcoyote.com
.idouga.com
forum.idsam.com
.idv.tw
ieasynews.net
.ied2k.net
ifanqiang.com
.ifanr.com
.ifcss.org
ifcss.org
ifjc.org
antidrm.hpg.ig.com.br
igfw.net
ignitedetroit.net
igvita.com
ihakka.net
iicns.com
illusionfactory.com
ilove80.be
im.tv
myvlog.im.tv
im88.tw
imageflea.com
imageshack.us
imagevenue.com
imagezilla.net
www.imdb.com
.img.ly
img.ly
.imkev.com
imkev.com
.imlive.com
immigration.gov.tw
tech2.in.com
incredibox.fr
.initiativesforchina.org
.inmediahk.net
inmediahk.net
innermongolia.org
instagram.com
interfaceaddiction.com
internationalrivers.org
internet.org
internetdefenseleague.org
internetfreedom.org
internetpopculture.com
inxian.com
iphonehacks.com
iphonix.fr
ipicture.ru
ipobar.com
ippotv.com
.iptorrents.com
iptorrents.com
ipvanish.com
iredmail.org
ironicsoftware.com
ironbigfools.compython.net
ironpython.net
.beta.iset.com.tw
beta.iset.com.tw
forum.iset.com.tw
.islam.org.hk
.islamicity.com
.isaacmao.com
isaacmao.com
isgreat.org
ismprofessional.net
isohunt.com
israbox.com
blog.istef.info
.istockphoto.com
isunaffairs.com
isuntv.com
itaboo.info
ithelp.ithome.com.tw
itshidden.com
.itweet.net
itweet.net
.iu45.com
ixquick.com
.izaobao.us
gmozomg.izihost.org
.izles.net
j.mp
blog.jackjia.com
whores.com
jbtalks.cc
jbtalks.com
jbtalks.my
jeanyim.com
jgoodies.com
jiaoyou8.com
.jiehua.cz
hk.jiepang.com
tw.jiepang.com
jieshibaobao.com
.jimoparty.com
jimoparty.com
jinbushe.org
zhao.jinhai.de
jingpin.org
ac.jiruan.net
jitouch.com
jkforum.net
research.jmsc.hku.hk
joachims.org
jobso.tv
joeedelman.com
journalofdemocracy.org
jpopforum.net
juliereyc.com
junauza.com
20.net
justfreevpn.com
tw.justin.tv
justtristan.com
juziyue.com
jwmusic.org
music.jwmusic.org
.jyxf.net
wai.com
.kagyuoffice.org.tw
kagyuoffice.org.tw
.kaiyuan.de
kakao.com
kanzhongguo.com
kanzhongguo.eu
karayou.com
kcsoftwares.com
.kechara.com
.keepandshare.com
.kendincos.net
.kenengba.com
kenengba.com
keontech.net
wiki.keso.cn
.khmusic.com.tw
bbs.kimy.com.tw
kingdomsalvation.org
kinghost.com
.kingstone.com.tw
killwall.com
.kissbbao.cn
.knowledgerush.com
kodingen.com
www.kodingen.com
kompozer.net
koolsolutions.com
.koornk.com
koornk.com
.kui.name
kun.im
kurtmunger.com
kusocity.com
kwongwah.com.my
kyohk.net
.kzeng.info
kzeng.info
forum.org
ladbrokes.com
labiennale.org
lagranepoca.com
.lalulalu.com
laogai.org
laomiu.com
.laoyang.info
laoyang.info
laptoplockdown.com
.laqingdan.net
larsgeorge.com
lastfm.es
latelinenews.com
lazarsearlymusic.com
leecheukyan.org
lematin.ch
.lemonde.fr
lenwhite.com
lerosua.org
blog.lester850.info
lesoir.be
letscorp.net
liansi.org
.lianyue.net
liaowangxizang.net
.liaowangxizang.net
liberal.org.hk
libertytimes.com.tw
.lidecheng.com
limiao.net
abitno.linpie.com
line.me
.linglingfa.com
.linkideo.com
api.linksalpha.com
apidocs.linksalpha.com
www.linksalpha.com
help.linksalpha.com
engineer.net
linuxconfig.org
linuxreviews.org
linuxtoy.org
.lipuman.com
listentoyoutube.com
listorious.com
liudejun.com
.liuhanyu.com
.liujianshu.com
liujianshu.com
liuxiaotong.com
liu.lu
.liveleak.com
liveleak.com
.livestation.com
livestream.com
livingonline.us
livingstream.com
livevideo.com
.livevideo.com
lizhizhuangbi.com
lkcn.net
localpresshk.com
lockdown.com
lockestek.com
logbot.net
logiqx.com
logmike.com
.longhair.hk
longtermly.net
.lookatgame.com
lookatgame.com
lookingglasstheatre.org
lookpic.com
.lotuslight.org.tw
hkreporter.loved.hk
lrfz.com
lrip.org
.lsd.org.hk
lsd.org.hk
lsforum.net
lsm.org
lsmchinese.org
lsmkorean.org
.lupm.org
lupm.org
lushstories.com
lvhai.org
mh4u.org
team.cc
www.macrovpn.com
ar.ch
maiplus.com
marc.info
marguerite.su
martincartoons.com
.maiio.net
archive.com
malaysiakini.com
makemymood.com
marines.mil
markmail.org*message
martau.com
maruta.be
.marxist.com
marxist.net
.marxists.org
matainja.com
badimon.com
matsushimakaede.com
mayimayi.com
mcadforums.com
mcfog.com
t.org
.mediafire.com
meetup.com
mefeedia.com
lich355.megabyet.net
.megaporn.com
megarotic.com
megavideo.com
megurineluka.com
meirixiaochao.com
peach.com
memedia.cn
.memrijttm.org
times.com.tw
.mesotw.com
.metacafe.com
meteorshowersonline.com
metrolife.ca
mgoon.com
mgstage.com
mhradio.org
michaelanti.com
michaelmarketl.com
way.net
.mihk.hk
mihua.org
.mimivip.com
minghui.org
school.org
.mingjinglishi.com
mingjinglishi.com
mingjingnews.com
mingpao.com
.mingpaocanada.com
.mingpaomonthly.com
mingpaonews.com
.mingpaony.com
.mingpaosf.com
.mingpaotor.com
.mingpaovan.com
.mininova.org
.minzhuhua.net
minzhuhua.net
minzhuzhongguo.org
miroguide.com
mirrorbooks.com
mitbbs.com
.mixero.com
mixero.com
mixpod.com
.mixx.com
mixx.com
mizzmona.com
.mk5000.com
.mlcool.com
mmaaxx.com
plurktop.mmdays.com
.mmmca.com
mobatek.net
.mobile01.com
mobileways.de
.mobypicture.com
moby.to
mrdoob.com
wiki.moegirl.org
mog.com
molihua.org
mondex.org
www.monlamit.org
c1522.mooo.com
monitorchina.org
bbs.morbell.com
morningsun.org
movabletype.com
moviefap.com
www.moztw.org
mp3ye.eu
mpettis.com
mpfinance.com
mpinews.com
mrtweet.com
news.msn.com.tw
.msguancha.com
mthruf.com
multiply.com
multiproxy.org
forum.mymaji.com
multiupload.com
muouju.com
muselinks.co.jp
muzi.com
muzi.net
mx981.com
proxy.com
forum.my903.com
myactimes.com
myaudiocast.com
.myav.com.tw
bbs.mychat.to
mychinamyhome.com
.mychinamyhome.com
www.mycould.com
myeclipseide.com
.myforum.com.hk
myforum.com.hk
myforum.com.uk
.myfreshnet.com
myparagliding.com
mypopescu.com
mysinablog.com
.myspace.com
naacoalition.org
old.nabble.com
naitik.net
namsisi.com
nanyang.com
.nanyangpost.com
nanyangpost.com
.nanzao.com
navicat.com
.nakido.com
nakido.com
.naol.ca
cyberghost.natado.com
lottery.co.uk
navy.mil
nccwatch.org.tw
.nch.com.tw
.ncn.org
ncn.org
etools.ncol.com
.nde.de
.ndr.de
www.ned.org
nekoslovakia.net
t.neolee.cn
netcolony.com
bolin.netfirms.com
zh.netlog.com
netme.cc
networkedblogs.com
neverforget8964.org
3lunch.net
akiba.com
.newcenturymc.com
newcenturymc.com
newcenturynews.com
newchen.com
.newchen.com
.newgrounds.com
newlandmagazine.com.au
news100.com.tw
.newscn.org
newscn.org
newsminer.com
newspeak.cc
.newsancai.com
newstapa.org
.newtaiwan.com.tw
newtalk.tw
newyorktimes.com
.nextmedia.com
static.apple.nextmedia.com
net.jp
nexttv.com.tw
nga.mil
ngensis.com
.nicovideo.jp
nighost.org
nintendium.com
.dayaarmongol.ning.com
dayaarmongol.ning.com
taiwanyes.ning.com
njactb.org
njuice.com
nlfreevpn.com
nobel.se
nobelprize.org
nobodycanstop.us
nokogiri.org
nokola.com
noobbox.com
novelasia.com
nownews.com
.nowtorrents.com
.noypf.com
noypf.com
npa.go.jp
.nps.gov
.nrk.no
nrk.no
nsc.gov.tw
ntdtv.co
ntdtv.ca
ntdtv.org
ntdtv.ru
cbs.ntu.edu.tw
nuexpo.com
.nuvid.com
nuzcom.com
.nvquan.org
.nydus.ca
nyt.com
nytco.com
.nytimes.com
nytimes.com
nytimg.com
nysingtao.com
nzchinese.net.nz
observechina.net
oclp.hk
review.org
offbeatchina.com
ogaoga.org
twtr2src.ogaoga.org
.oikos.com.tw
.oiktv.com
oizoblog.com
.okayfreedom.com
cat.net
olumpo.com
.olympicwatch.org
omgili.com
omnitalk.com
forum.omy.sg
news.omy.sg
showbiz.omy.sg
.on.cc
onedrive.live.com
.onlylady.cn
onmoon.net
onmoon.com
.oopsforum.com
open.com.hk
opendemocracy.net
myopenid.com
openid.net
blog.openinkpot.org
.openleaks.org
openleaks.org
openvpn.net
openwebster.com
help.opera.com
my.opera.com
demo.opera
opnir.com
www.orchidbbs.com
doll.com
orientaldaily.com.my
orn.jp
t.orzdream.com
tui.orzdream.com
orzistic.org
osfoora.com
m.oulove.org
ourdearamy.com
oursogo.com
oursteps.com.au
xinqimeng.over
share.ovi.com
owl.li
ht.ly
htl.li
mash.to
www.owind.com
www.oxid.it
oyax.com
.ozchinese.com
ow.ly
bbs.ozchinese.com
.ozyoyo.com
.pacificpoker.com
.packetix.net
page2rss.com
pagodabox.com
paint.net
coveringweb.com
.palacemoon.com
forum.palmislife.com
replika.com
eriversoft.com
panoramio.com
paper.li
paperb.us
.panluan.net
panluan.net
.panoramio.com
pao.net
.parade.com
pastebin.com
.pastie.org
pastie.org
blog.pathtosharepoint.com
pbs.org
pbwiki.com
pbworks.com
developers.box.net
wiki.oauth.net
wiki.phonegap.com
wiki.jqueryui.com
pbxes.com
pbxes.org
.pcdiscuss.com
pcdvd.com.tw
.pchome.com.tw
pcij.org
pct.org.tw
pdetails.com
pdproxy.com
peacefire.org
peacehall.com
.peeasian.com
.pekingduck.org
pekingduck.org
penchinese.com
penchinese.net
.penchinese.net
pengyulong.com
blog.pentalogic.net
.penthouse.com
.peopo.org
peopo.org
.percy.in
perfectvpn.net
perfspot.com
perlhowto.com
philly.com
photofocus.com
phuquocservices.com
.picidae.net
.picturedip.com
picturesocial.com
.pidown.com
.pign.net
blog.pilotmoon.com
.pin6.com
pin6.com
.ping.fm
ping.fm
n.com
.piring.com
pixelqi.com
css.pixnet.in
pixnet.net
.pixnet.net
.pk.com
placemix.com
pictures.playboy.com
playboy.com
plays.com.tw
m.plixi.com
plm.org.hk
plunder.com
.plus28.com
.plusbb.com
.pmates.com
po2b.com
podictionary.com
.pokerstars.com
pokerstars.com
zh.pokerstrategy.com
politicalchina.org
popyard.com
popyard.org
.porn.com
.porn2.com
.pornbase.org
.pornhub.com
pornmm.net
.pornoxo.com
.pornrapidshare.com
pornrapidshare.com
.pornstarclub.com
.porntube.com
.pornvisit.com
postadult.com
powercx.com
www.powerpointninja.com
cdn.printfriendly.com
pts.org.tw
pubu.com.tw
puffinbrowser.com
post.ly
.posterous.com
posterous.com
post.anyu.org
bralio.com
calebelston.com
designerol.com
blog.fizzik.com
nf.id.au
markmilian.com
log.riku.me
sogrady.me
vatn.org
veempiire.com
www.vegorpedersen.com
ventureswell.com
webfee.tk
whereiswerner.com
bill.zhong.pp.ru
.power.com
power.com
powerapple.com
abc.pp.ru
heix.pp.ru
prayforchina.net
premeforwindows7.com
presentationzen.com
privacybox.de
privateinternetaccess.com
privatepaste.com
privatetunnel.com
procopytips.com
provideocoalition.com
prosiben.de
proxifier.com
api.proxlet.com
proxomitron.info
proxy.org
.proxypy.net
proxypy.net
proxyroad.com
prozz.net
psblog.name
psiphon.ca
.ptt.cc
.puffstore.com
pullfolio.com
pureconcepts.net
purepdf.com
purevpn.com
.putlocker.com
pwned.com
python.com
.python.com.tw
python.com.tw
.qanote.com
qanote.com
gong.me
.qidian.ca
.qienkuen.org
qienkuen.org
qiwen.lu
qixianglu.cn
bbs.qmzdd.com
.qkshare.com
qoos.com
blog.qooza.hk*dafengqixi
efksoft.com
qstatus.com
qtweeter.com
qtrac.eu
quadedge.com
www.getyouram.com
hiitch.com
qusi8.net
.qvodzy.org
nemesis2.qx.net*pages*MyEnTunnel
qxbbs.org
.radicalparty.org
radioaustralia.net.au
opml.radiotime.com
radiovaticana.org
radiovncr.com
raidcall.com.tw
rangzen.org
blog.ranxiang.com
ranyunfei.com
.rapbull.net
rapidshare8.com
.rapidsharedata.com
rcinet.ca
.read100.com
.readingtimes.com.tw
readingtimes.com.tw
readmoo.com
.realraptalk.com
.recordhistory.org
redchinacn.org
.redtube.com
referer.us
reflectivecode.com
relaxbbs.com
renminbao.com
.renyurenquan.org
renyurenquan.org
subacme.rerouted.org
.revleft.com
retweetist.com
retweetrank.com
connectedchina.reuters.com
www.reuters.com
revver.com
.rfa.org
.rfachina.com
.rfamobile.org
rferl.org
.rfi.fr
rfi.fr
rfi.my
.rhcloud.com
vds.rightster.com
.rileyguide.com
riku.me
.rlwlw.com
rlwlw.com
.rmjdw.com
chinese.rnw.nl
.rnw.nl
robtex.com
robustnessiskey.com
rocmp.org
rojo.com
ronjoneswriter.com
.roodo.com
.rotten.com
.rsf.org
rsf.org
chinese.org
.rssmeme.com
rssmeme.com
.rthk.hk
rthk.hk
.rthk.org.hk
rthk.org.hk
rti.org.tw
.ruanyifeng.com
.rushbee.com
rutube.ru
.ruyiseek.com
.rxhj.net
s1heng.com
s8forum.com
sacom.hk
sadpanda.us
.saiq.me
saiq.me
.salvation.org.hk
salvation.org.hk
.samair.ru
sammyjs.org
sandnoble.com
sankaizok.com
.sanmin.com.tw
sapikachu.net
savemedia.com
savetibet.de
savetibet.fr
savetibet.nl
savetibet.org
savetibet.ru
savevid.com
say2.info
.scmp.com
.scmpchinese.com
.scribd.com
scriptspot.com
seapuff.com
domainhelp.search.com
secretchina.com
secretgarden.no
default.secureserver.net
securitykiss.com
seesmic.com
seevpn.com
seezone.net
sejie.com
.sendspace.com
tweets.seraph.me
sesawe.net
.sesawe.org
sethwklein.net
forum.setty.com.tw
.sevenload.com
sevenload.com
.sex.com
11.com
sex3.com
.sex8.cc
.sexandsubmission.com
.sexhu.com
.sexhuang.com
sexinsex.net
67.220.91.18
67.220.91.23
.sf.net
.sfileydy.com
shadow.ma
shadowsocks.org
english.com
.shangfang.org
shangfang.org
shapeservices.com
.sharebee.com
sharecool.org
sharkdolphin.com
sharpdaily.com.hk
.sharpdaily.hk
.shaunthesheep.com
shaunthesheep.com
sheikyermami.com
shellmix.com
shenshou.org
shenyunperformingarts.org
shenzhoufilm.com
shinychan.com
.shitaotv.org
shixiao.org
shizhao.org
.shizhao.org
shkspr.mobi
shodanhq.com
.shopping.com
.showtime.jp
ch.shvoong.com
.shwchurch3.com
shwchurch3.com
simplecd.org
simplecd.me
simpleproductivityblog.com
bbs.sina.com
blog.sina.com.tw
dailynews.sina.com
forum.sina.com.hk
home.sina.com
magazines.sina.com.tw
news.sina.com.hk
news.sina.com.tw
singtao.com
news.singtao.ca
cdp.sinica.edu.tw
monthly.com
sinocast.com
sinocism.com
sinomontreal.ca
.sinonet.ca
.sinopitt.info
.sinoants.com
sinoants.com
sinoquebec.com
site90.net
.sitebro.tw
siteks.uk.to
sitemaps.org
sitetag.us
sis.xxx
sis001.com
sis001.us
sjum.cn
skimtube.com
skybet.com
skyhighpremium.com
bbs.skykiwi.com
www.skype.com
skyvegas.com
.xskywalker.com
xskywalker.com
m.slandr.net
slavasoft.com
slheng.com
.slideshare.net
forum.slime.com.tw
.slutload.com
smhric.org
sndcdn.com
ga.net
home.so
soc.mil
sockslist.net
.sod.co.jp
.softether.org
softether.org
download.com
sogclub.com
sohcradio.com
www.somee.com
algorithms.com
.soumo.info
soup.io
static.soup.io
.slinkset.com
slickvpn.com
snapchat.com
.snaptu.com
snaptu.com
sneakme.net
snooper.co.uk
.sobees.com
sobees.com
socialwhale.com
.softether.co.jp
softwarebychuck.com
blog.sogoo.org
soh.tw
sohfrance.org
chinese.soifind.com
sokamonline.com
somee.com
.songjianjun.com
songjianjun.com
.sonidodelaesperanza.org
.sopcast.com
.sopcast.org
soundcloud.com
.soundofhope.kr
soundofhope.org
soupofmedia.com
.sourceforge.net
southnews.com.tw
sowers.org.hk
wlx.sowiki.net
scape.com
.spankwire.com
spb.com
spencertipping.com
spinejs.com
sproutcore.com
squarespace.com
ssh91.com
www.stackfile.com
standupfortibet.org
usinfo.state.gov
.starp2p.com
starp2p.com
startpage.com
.state168.com
storm.com
sthoo.com
.stickam.com
stickeraction.com
stonegames.net
stoneip.info
storagenewsletter.com
.stoptibetcrisis.net
stoptibetcrisis.net
stoweboyd.com
streamingthe.net
cn.streetvoice.com
cn2.streetvoice.com
tw.streetvoice.com
strongvpn.com
.student.tw
stupidvideos.com
.sugarsync.com
sugarsync.com
summify.com
sun1911.com
.suoluo.org
api.supertweet.net
www.supertweet.net
.surfeasy.com.au
request.py
static.py
svwind.com
sweux.com
tools.net
.sydneytoday.com
.sylfoundation.org
syncback.com
sysadmin1138.net
sysresccd.org
.sytes.net
blog.syx86.com
blog.syx86.cn
.szbbs.net
szetowah.org.hk
.t35.com
.t66y.com
t66y.com
usa.org
tabtter.jp
.tacem.org
tafaward.com
tagwalk.com
taipei.gov.tw
.taipeisociety.org
taipeisociety.org
.taiwandaily.net
taiwantt.org.tw
taiwandaily.net
taiwankiss.com
taiwannation.com
taiwannation.com.tw
taiwannews.com.tw
taiwanus.net
taiwanyes.com
sex.com
tamiaode.tk
tanc.org
tangben.com
.taolun.info
taolun.info
blog.taragana.com
.taweet.com
taweet.com
tbpic.info
tbsec.org
tbsn.org
.tbsseattle.org
tchrd.org
tcno.net*doc*tor
teamseesmic.com
.teashark.com
techlifeweb.com
techparaiso.com
teck.in
.telecomspace.com
telegraph.co.uk
.tenacy.com
theampfactory.com
theappleblog.com
belli.com
usa.com
theblemish.com
thebcomplex.com
.thechinabeat.org
thedieline.com
thedw.us
thegatesnotes.com
thegioitinhoc.vn
thehousenews.com
thehun.net
thelifeyoucansave.com
thelius.org
thepiratebay.org
thepiratebay.se
theqii.info
thereallove.kr
thesartorialist.com
thespeeder.com
thetibetpost.com
thetrotskymovie.com
thevivekspot.com
thewgo.org
.thisav.com
thisav.com
thkphoto.com
thomasbernhard.org
threatchaos.com
throughnightsfire.com
.thumbzilla.com
thywords.com
tiananmenmother.org
tiananmenuniv.com
tiananmenuniv.net
tiandixing.org
.tianhuayuan.com
tiantibooks.org
.tianzhu.org
.tibet.at
.tibet.com
tibet.com
.tibet.net
tibet.net
tibet.org.tw
tibetalk.com
.tibetanyouthcongress.org
tibetanyouthcongress.org
.tibetcorps.org
tibetfund.org
.tibetjustice.org
tibetoffice.org
tibetonline.com
tibetonline.tv
.tibetonline.tv
.tibetsun.com
tibetwrites.org
.time.com
blog.tiney.com
tinychat.com
tinypaste.com
tidyread.com
.tistory.com
collins.com
tkforum.tk
.tmagazine.com
tmagazine.com
tmi.me
.tnaflix.com
tnaflix.com
togetter.com
247.com
hot.com
tokyocn.com
oka.jp
tonyyan.net
.toodoc.com
toonel.net
.topnews.in
topshare.us
.topshareware.com
topstyle4.com
topsy.com
tora.to
.torproject.org
torproject.org
torrentcrazy.com
torvpn.com
touch99.com
toutfr.com
.tpi.org.tw
tpi.org.tw
transgressionism.org
transparency.org
travelinlocal.com
trendsmap.com
.trialofccp.org
trialofccp.org
tripod.com
www.tripod.com
.trouw.nl
.trt.net.tr
trtc.com.tw
trulyergonomic.com
trustedbi.com
.truth101.co.tv
truth101.co.tv
truthcn.com
.truveo.com
.tsemtulku.com
tsquare.tv
tsunagarumon.com
www.tsuru
.tsctv.net
tt1069.com
tttan.com
.tttan.com
bb.ttv.com.tw
.tuanzt.com
.tube.com
tube8.com
tubecao.com
tubewolf.com
tuidang.net
tuidang.org
bbs.tuitui.info
tumutanzi.com
.tunein.com
tunein.com
tunnelbear.com
.turbobit.net
turbobit.net
turningtorso.com
tuxtraining.com
301works.org
365singles.com.ar
interesting.com
porn.com
news.atebits.com
tumblr.awflasher.com
badassjs.com
basetimesheightdividedby2.com
benjaminste.in
blog.birdhouseapp.com
bobulate.com
bonjourlesgeeks.com
bookshelfporn.com
blog.boxcar.io
blog.bitly.com
chevronwp7.com
clientsfromhell.net
codeboxapp.com
cookingtothegoodlife.com
cubicle17.com
photos.dailyme.com
davidslog.com
blog.davidziegler.net
blog.dayoneapp.com
drewolanoff.com
blog.dribbble.com
chaos.e
eamonnbrennan.com
carry.com
eyespirit.info
life.fly4ever.me
fredwilson.vc
fuckgfw.com
geekmade.co.uk
generesis.com
news.ghostery.com
givemesomethingtoread.com
blog.gowalla.com
heiyo.info
hellonewyork.us
blog.hotpotato.com
ialmostlaugh.com
blog.ifttt.com
blog.instagram.com
blog.instapaper.com
interestinglaugh.com
blog.iphone
jayparkinsonmd.com
blog.joeyrobert.org
kt.kcome.org
my.keso.cn
blog.kickstarter.com
blog.kl.am
blog.klip.me
t.kun.im
blog.lightbox.com
littlebigdetails.com
lovequicksilver.com
lyricsquote.com
madmenunbuttoned.com
marco.org
minimalmac.com
mixedmedialabs.com
modfetish.com
blog.mongodb.org
navigeaters.com
london.neighborhoodr.com
blog.path.com
parislemon.com
blog.pikchur.com
blog.rockmelt.com
blog.romanandreg.com
solozorro.tk
blog.sparrowmailapp.com
stuffimreading.com
blog.summify.com
thedailywh.at
theinternetwishlist.com
thisiswhyyouarefat.com
www.tiffanyarment.com
tjholowaychuk.com
tomsc.com
blog.topify.com
thehungrydudes.com
tumblweed.org
status.twhirl.org
blog.usa.gov
photo.utom.us
state.org
wellplacedpixels.com
whydidyoubuymethat.com
wordboner.com
wordsandturds.com
worstthingieverate.com
xmusic.fm
xuzhuoer.com
bd.zhe.la
cocoa.zonble.net
.tv.com
www.tv.com
tv.com
intros.com
tvants.com
forum.tvb.com
tvboxnow.com
tvider.com
tvunetworks.com
npo.org
twapperkeeper.com
twaud.io
.twaud.io
.twbbs.net.tw
twbbs.org
twbbs.tw
twblogger.com
tweepmag.com
.tweepml.org
tweepml.org
.tweetbackup.com
tweetbackup.com
tweetboard.com
.tweetboner.biz
tweetboner.biz
.tweetdeck.com
tweetdeck.com
deck.ly
mtw.tl
tweetedtimes.com
tweetmylast.fm
tweetphoto.com
tweetrans.com
tweetree.com
tweetwally.com
tweetymail.com
twftp.org
twibase.com
.twibble.de
twibble.de
twibbon.com
twibs.com
twicsy.com
.twifan.com
twifan.com
twiffo.com
twilog.org
twimbow.com
twindexx.com
twipple.jp
twip.me
twistar.cc
twisternow.com
twistory.net
twitbrowser.net
twitcause.com
twitgether.com
twiggit.org
twitgoo.com
twitiq.com
.twitlonger.com
twitlonger.com
tl.gd
twitoaster.com
twitonmsn.com
.twitpic.com
twitpic.com
twitreferral.com
.twit2d.com
twit2d.com
.twitstat.com
twitstat.com
dotheyfolloweachother.com
firstfivefollowers.com
retweeteffect.com
tweeplike.me
tweepguide.com
turbotwitter.com
.twitvid.com
twitvid.com
199.59.148.20
t.co
twt.tl
twittbot.net
twitter.com
twitter.jp
twttr.com
twitter4j.org
.twittercounter.com
twittercounter.com
twitterfeed.com
.twittergadget.com
twittergadget.com
.twitterkr.com
twitterkr.com
twittermail.com
twittertim.es
twitthat.com
twitturk.com
.twitturly.com
twitturly.com
.twitzap.com
twiyia.com
.twreg.info
twreg.info
twstar.net
.twtkr.com
twtkr.com
twimg.com
twtrland.com
twurl.nl
.twyac.org
twyac.org
.tycool.com
tycool.com
tynsoe.org
tzangms.com
typepad.com
www.typepad.com
static.typepad.com
blog.expofutures.com
legaltech.law.com
www.loiclemeur.com
latimesblogs.latimes.com
blog.palm.com
blogs.tampabay.com
contests.twilio.com
embr.in
guomin.us
uberproxy.net
.srcf.ucam.org
ucdc1998.org
.uchicago.edu
uderzo.it
udn.com
.udn.com
ufreevpn.com
.ugo.com
uhrp.org
uighurbiz.net
.ulike.net
ukliferadio.co.uk
ultravpn.fr
ultraxs.com
unblock.cn.com
unblocksit.es
uncyclomedia.org
uncyclopedia.info
uncyclopedia.tw
unholyknight.com
.uni.cc
unicode.org
.uniteddaily.com.my
.unix100.com
unknownspace.org
unpo.org
uocn.org
tor.updatestar.com
.upload4u.info
.uploaded.to
uploaded.to
.uploadstation.com
www.urbanoutfitters.com
myshare.url.com.tw
urlborg.com
urlparser.com
us.to
usacn.com
beta.usejump.com
usfk.mil
earthquake.usgs.gov
usmc.mil
.ustream.tv
ustream.tv
usus.cc
.uushare.com
uushare.com
.uwants.com
.uwants.net
uyghurcongress.org
uygur.org
v70.us
v7976888.info
vaayoo.com
domain.com
.van698.com
.vanemu.cn
jp.com
vansky.com
vapurl.com
online.org
vcfbuilder.org
.velkaepocha.sk
.venbbs.com
.venchina.com
veoh.com
.verizon.net
verybs.com
.vft.com.tw
videobam.com
.videomo.com
vidoemo.com
viki.com
vimeo.com
vimgolf.com
vimperator.org
vincnd.com
vinniev.com
video.tiscali.it
.vllcs.org
vmixcore.com
cn.voa.mobi
tw.voa.mobi
.voachineseblog.com
voachineseblog.com
voagd.com
voacantonese.com
voachinese.com
voatibetan.com
.voanews.com
vocn.tv
.vot.org
vot.org
www.voy.com
www.vpncup.com
vpnbook.com
vpnfire.com
vpngate.jp
.vpngate.net
vpngate.net
vpnpop.com
vpnpronet.com
vtunnel.com
lists.w3.org
waffle1999.com
.jyzj.waqn.com
jyzj.waqn.com
.wahas.com
.waigaobu.com
waikeung.org
.waiwaier.com
waiwaier.com
wallornot.org
wallpapercasa.com
www.wan
wanderinghorse.net
wangafu.net
wangjinbo.org
.wangjinbo.org
wanglixiong.com
wangruoshui.net
www.wangruowang.org
daily.com
wapedia.mobi
.wattpad.com
wattpad.com
.makzhou.warehouse333.com
washeng.net
.wdf5.com
.wearn.com
wearn.com
hudatoriq.web.id
web2project.net
webbang.net
weblagu.com
webmproject.org
tv.net
webshots.com
websitepulse.com
webworkerdaily.com
weeewooo.net
.weekmag.info
.wefong.com
weiboleak.com
weijingsheng.org
.weiming.info
weiquanwang.org
weisuo.ws
wengewang.com
.wengewang.org
wengewang.org
.wenhui.ch
wenku.com
blog.wenweipo.com
wenxuecity.com
.wenyunchao.com
wenyunchao.com
westca.com
westernwolves.com
hkg.westkit.net
www.wet123.com
wepn.info
wetpussygames.com
.wetplace.com
wexiaobo.org
wezhiyong.org
wezone.net
.wforum.com
wforum.com
.whatblocked.com
whatblocked.com
.whippedass.com
whylover.com
whyx.org
evchk.wikia.com
cn.uncyclopedia.wikia.com
zh.uncyclopedia.wikia.com
wikileaks.ch
wikileaks.de
wikileaks.eu
wikileaks.lu
.wikileaks.org
wikileaks.org
wikileaks.pl
collateralmurder.com
collateralmurder.org
wikilivres.info
wikimapia.org
secure.wikimedia.org
wikimedia.org.mo
zh.wikinews.org
wikiwiki.jp
sports.williamhill.com
willw.net
windowsphoneme.com
winwhispers.info
wiredbytes.com
wiredpen.com
.wisevid.com
wisevid.com
.witnessleeteaching.com
.witopia.net
.wo.tc
woeser.com
wolfax.com
.womensrightsofchina.org
womensrightsofchina.org
woopie.jp
woopie.tv
workatruna.com
.worldcat.org
worldjournal.com
.wordpress.com
wordpress.com
woxinghuiguo.com
life.net
.wpoforum.com
wpoforum.com
.wqlhw.com
.wqyd.org
wqyd.org
wrchina.org
wretch.cc
.wsj.com
.wtfpeople.com
.wuala.com
wuerkaixi.com
wufi.org.tw
wujie.net
wujieliulan.com
wukangrui.net
wwitv.com
wzyboy.im
www.x
art.com
wall.org
x1949x.com
x365x.com
xanga.com
xbabe.com
.xbookcn.com
xbookcn.com
xcafe.in
x.xcity.jp
.xcritic.com
destiny.xfiles.to
.xfm.pp.ru
xgmyd.com
xh4n.cn
xhamster.com
one.xthost.info
.xiaochuncnjp.com
s.xiaod.in
.xiaohexie.com
xiaoma.org
xiaohexie.com
xiezhua.com
.xing.com
xing.com
.xinmiao.com.hk
xinmiao.com.hk
xinsheng.net
xinshijue.com
xinhuanet.org
xinyubbs.net
zhiye.org
xjp.cc
guide.com
xmovies.com
xnxx.com
xpdo.net
xpud.org
k2.xrea.com
xtube.com
blog.xuite.net
vlog.xuite.net
xuzhiyong.net
xuchao.org
xuchao.net
xvedios.com
.xvideos.com
.xxbbx.com
xxxx.com.au
xys.org
xysblogs.org
xyy69.com
xyy69.info
page.bid.yahoo.com
blogs.yahoo.co.jp
buy.yahoo.com.tw
hk.yahoo.com
hk.knowledge.yahoo.com
hk.myblog.yahoo.com
hk.news.yahoo.com
hk.rd.yahoo.com
hk.search.yahoo.com
hk.video.news.yahoo.com
meme.yahoo.com
tw.yahoo.com
tw.myblog.yahoo.com
tw.news.yahoo.com
pulse.yahoo.com
upcoming.yahoo.com
video.yahoo.com
yahoo.com.hk
yam.com
yasni.co.uk
yasukuni.or.jp
.ydy.com
yeelou.com
yeeyi.com
yegle.net
yfrog.com
yhcw.net
.yi.org
.yidio.com
yidio.com
yilubbs.com
xa.yimg.com
.yipub.com
yipub.com
.yogichen.org
yogichen.org
yong.hu
.yorkbbs.ca
youxu.info
.yyii.org
yyii.org
.yzzk.com
yzzk.com
.youjizz.com
youjizz.com
youmaker.com
youpai.org
freedom.net
.yousendit.com
yousendit.com
youthbao.com
.youthnetradio.org
blog.youthwant.com.tw
share.youthwant.com.tw
topic.youthwant.com.tw
.youporn.com
youporn.com
youtu.be
.youtube.com
youtube.com
nocookie.com
.youtubecn.com
youversion.com
blog.youxu.info
ytimg.com
ytht.net
yuanming.net
yunchao.net
yvesgeleyn.com
yx51.net
yymaya.com
zacebook.com
zannel.com
tap11.com
luntan.zaobao.com
.zaobao.com.sg
zaobao.com.sg
.zaozon.com
zarias.com
www.zaurus.org.uk
.zdnet.com.tw
.zengjinyan.org
zeutch.com
www.zfreet.com
zgzcjj.net
.zhanbin.net
zhanbin.net
zhenghui.org
zhenlibu.info
.zhinengluyou.com
zhongguotese.net
zhongmeng.org
zhreader.com
zhuichaguoji.org
.ziddu.com
zillionk.com
zinio.com
ziplib.com
.zkaip.com
zkaip.com
zlib.net
zmw.cn
zomobo.net
.zonaeuropa.com
zonaeuropa.com
zootool.com
.zoozle.net
writer.zoho.com
.zshare.net
.zsrhao.com
.zuo.la
zuo.la
.zuola.com
zuola.com
zvereff.com
zyzc9.com
upload.wikimedia.org
.wikipedia.org
ar.wikipedia.org*
yue.wikipedia.org
en.wikipedia.org
zh.wikipedia.org
zh.m.wikipedia.org
zh.wikisource.org
zh.wikipedia.org*2012
zh.wikipedia.org*2014
zh.wikipedia.org*512
zh.wikipedia.org*08
zh.wikipedia.org*1959
zh.wikipedia.org*1989
zh.wikipedia.org*610
zh.wikipedia.org*Anti
zh.wikipedia.org*
zh.wikipedia.org*GFW
zh.wikipedia.org*Google
yue.wikipedia.org*
zh.wikibooks.org*
gov.tw
tax.nat.gov.tw
moe.gov.tw
cwb.gov.tw
npm.gov.tw
yatsen.gov.tw
aec.gov.tw
mvdis.gov.tw
stdtime.gov.tw
nmmba.gov.tw
ntdmh.gov.tw
grb.gov.tw
tpde.aide.gov.tw
news.gov.tw
nerhl.gov.tw
house.gov.tw
vghtc.gov.tw
aide.gov.tw
hchcc.gov.tw
ntuh.gov.tw
nhri.gov.tw
nstm.gov.tw
ntsec.gov.tw
ner.gov.tw
nmtl.gov.tw
ntl.gov.tw
pet.gov.tw
khcc.gov.tw
khms.gov.tw
wanfang.gov.tw
nict.gov.tw
arte.gov.tw
nmh.gov.tw
nmp.gov.tw
tphcc.gov.tw
iner.gov.tw
tncsec.gov.tw
nspo.gov.tw
ncree.gov.tw
vghks.gov.tw
tchb.gov.tw
pabp.gov.tw
itrc.gov.tw
df.gov.tw
womenbusiness.nyc.gov.tw
cert.nat.gov.tw
kk.gov.tw
thbstc.gov.tw
comnews.gio.gov.tw
klccab.gov.tw
yvtc.gov.tw
aftygh.gov.tw
klra.gov.tw
lungtanhr.gov.tw
taoyuan.gov.tw
hcc.gov.tw
nvri.gov.tw
nmvttc.gov.tw
kmh.gov.tw
patehr.gov.tw
nerch.gov.tw
kmseh.gov.tw
nertt.gov.tw
cycab.gov.tw
chukuang.gov.tw
gysd.nyc.gov.tw
vghtpe.gov.tw
etraining.gov.tw
stag.gov.tw
bdhr.gov.tw
tcsac.gov.tw
imagesblog.gio.gov.tw
dmtip.gov.tw
chccc.gov.tw
hengchuen.gov.tw
cc.gov.tw
921.gov.tw
ncdr.nat.gov.tw
4pppc.gov.tw
klsio.gov.tw
nici.nat.gov.tw
cromotc.nat.gov.tw
174.142.105.153
69.65.19.160
aliyun.com
baidu.com
jike.com
chinaso.com
qq.com
sina.cn
sina.com.cn
sogou.com
so.com
soso.com
yahoo.cn
youdao.com
zhongsou.com
autoproxy.org
ime.baidu.jp
google.com
google.co.jp
google.co.hk
bbc.co.uk
github.com
wikipedia.org
amazonaws.com
akamai.net
akamaiedge.net
cloudfront.net